export const FETCHED_DETAILED_PRODUCT = "FETCHED_DETAILED_PRODUCT";
export const FETCHED_ALL_PRODUCTS = "FETCHED_ALL_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
